joinfaces:
  faces:
    PROJECT_STAGE: Development
  primefaces:
    theme: admin
    
spring:
  mail:
    host: email-smtp.us-east-1.amazonaws.com
    port: 587
    username: ses-smtp-user.20230922-194515
    fromUserEmail: shailendramishra.ind@gmail.com
    fromUserFullName: TeamWrapAround
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# Set the context path
server:
  servlet:
    context-path: /notification-api

amazon:
  aws:
    accesskey: sdvdsgvdsag
    secretkey: fsdvdgdsaggasd